const taxes = [
  {
    name: "NONE",
    type: "single",
    description: "None with 0% rate",
    category: "none",
    children: [],
    percentage: 0,
  },
  {
    name: "SGST@9",
    type: "single",
    description: "SGST with 9 % rate",
    category: "sgst",
    children: [],
    percentage: 9,
  },
  {
    name: "CGSTt@9",
    type: "single",
    description: "cgst with 9 % rate",
    category: "cgst",
    children: [],
    percentage: 9,
  },
  {
    name: "SGST@14",
    type: "single",
    description: "SGST with 14% rate",
    category: "sgst",
    children: [],
    percentage: 14,
  },
  {
    name: "CGST@14",
    type: "single",
    description: "cgst with  14% rate",
    category: "cgst",
    children: [],
    percentage: 14,
  },
  {
    name: "CGST@2.5",
    type: "single",
    description: "sgst with 2.5% rate",
    category: "sgst",
    children: [],
    percentage: 2.5,
  },
  {
    name: "CGST@2.5",
    type: "single",
    description: "cgst with 2.5% rate",
    category: "cgst",
    children: [],
    percentage: 2.5,
  },
  {
    name: "CGST@6",
    type: "single",
    description: "sgst with 6% rate",
    category: "sgst",
    children: [],
    percentage: 6,
  },
  {
    name: "CGST@6",
    type: "single",
    description: "cgst with 6% rate",
    category: "cgst",
    children: [],
    percentage: 6,
  },
  {
    name: "SGST@0.125",
    type: "single",
    description: "sgst with 0.125% rate",
    category: "sgst",
    children: [],
    percentage: 0.125,
  },
  {
    name: "CGST@0.125",
    type: "single",
    description: "cgst with 0.125% rate",
    category: "cgst",
    children: [],
    percentage: 0.125,
  },
  {
    name: "CGST@1.5",
    type: "single",
    description: "cgst with 1.5% rate",
    category: "cgst",
    children: [],
    percentage: 1.5,
  },
  {
    name: "SGST@1.5",
    type: "single",
    description: "SGST with 1.5% rate",
    category: "sgst",
    children: [],
    percentage: 1.5,
  },
  {
    name: "IGST@0.25",
    type: "single",
    description: "igst with 0.25% rate",
    category: "igst",
    children: [],
    percentage: 0.25,
  },
  {
    name: "IGST@3",
    type: "single",
    description: "igst with 3% rate",
    category: "igst",
    children: [],
    percentage: 3,
  },
  {
    name: "IGST@5",
    type: "single",
    description: "igst with 5% rate",
    category: "igst",
    children: [],
    percentage: 5,
  },
  {
    name: "IGST@12",
    type: "single",
    description: "igst with 12% rate",
    category: "igst",
    children: [],
    percentage: 12,
  },
  {
    name: "IGST@18",
    type: "single",
    description: "igst with 18% rate",
    category: "igst",
    children: [],
    percentage: 18,
  },
  {
    name: "IGST@28",
    type: "single",
    description: "igst with 28% rate",
    category: "igst",
    children: [],
    percentage: 28,
  },
];

module.exports = taxes;
